#pragma once

#define ACTION_BACKED_ACCELERATION_THRESHOLD 1e-7f
#define MIN_ALIGNED_LINEAR_VELOCITY_CHANGE_DURATION_THRESHOLD 1.0f
#define MIN_ALIGNED_LINEAR_VELOCITY_DIFF_THRESHOLD 1e-3f

#define MIN_LANE_CHANGE_DURATION_THRESHOLD 2.5f

#define MAX_ALIGNED_LINEAR_ACCELERATION 3.5e-6f
#define MIN_ALIGNED_LINEAR_ACCELERATION -6.56e-6f
