#pragma once

#define OPERATING_FRAMERATE 10.0f

#define GAUSSIAN_KERNEL_SIZE 7
#define GAUSSIAN_STD_DEV (GAUSSIAN_KERNEL_SIZE / 6.0f)

#define ACTION_BACKED_ACCELERATION_THRESHOLD 1e-7
#define MIN_ALIGNED_LINEAR_VELOCITY_CHANGE_DURATION_THRESHOLD 1.0f
#define MIN_ALIGNED_LINEAR_VELOCITY_DIFF_THRESHOLD 1e-3

#define MIN_LANE_CHANGE_DURATION_THRESHOLD 2.5f
